---
# tasks file for fch.gitUpload

   - name: add file to git
     command: git add * chdir={{ tempDir }}

   - name: commit changes
     command: git commit -m "Automated Changes" chdir={{ tempDir }}

#   - name: Test we can push to git remote location
#     authorized_keys:
#       user: "{{ git_user }}"
#       state: present
#       key: "{{ item_key }}"
#     with_items: "{{ gitpush_ssh_keys }}"
#     loop_control:
#       loop_var: item_key

#   - name: Push Repo
#     local_action: "command git --git-dir=\"{{ playbook_dir }}/{{ gitpush_local_repo_path }}\" push \"{{ gitpush_user|default(ansible_user) }}{% if gitpush_user %}@{% endif %}{{ gitpush_host }}:{{ gitpush_repo_path }}\" HEAD:master {{ gitpush_additional_params }}"
#  changed_when: response.stderr != "Everything up-to-date"
#  register: response
#  become: no
#  notify: "{{ notify }}"


   - name: push changes to repo
     command: git push -u origin master chdir={{ tempDir }}
